[package]
name = "patch-hub-proc-macros"
version = "0.1.0"
edition = "2021"
description = "Crate for patch-hub procedural macros"
license = "GPL-2.0"

[dependencies]
derive-getters = { version = "0.5.0", features = ["auto_copy_getters"] }
lazy_static = "1.5.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
syn = { version = "2.0.111", features = ["full"] }
quote = "1.0.42"
proc-macro2 = "1.0.103"

[lib]
proc-macro = true
doctest = false # otherwise tests will fail
